Fe 847 clean component library
uniwhales/component-library pull request #161
Opened 2023-02-20 11:44 UTC by shan8851

# Description

remove unused components and update theme object

---

Fixes # (issue)
https://uniwhales.atlassian.net/browse/FE-847?atlOrigin=eyJpIjoiOGRmMjMyZmI2ZThkNDBkMmFkMzNhOWI3YTU4M2NiYjYiLCJwIjoiaiJ9

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**Test Configuration**:
* Hardware: Android/iphone/macbook/pc/laptop

## Was this feature tested on all the browsers?

- [x] Chrome/Brave
- [] Firefox
- [] Safari 

# Checklist:

- [x] I have performed a self-review of my code
- [x] I have tested my changes
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] Storybook covers all new/pre-existing variations without need to change controls to test it
- [x] I have upgraded version in package.json
- [x] I have assigned QA and Reviewers
- [x] I have labeled the PR accordingly
- [ ] I have updated time spent in my jira ticket
- [ ] Build succeeded

---

## Notes for QA

## Notes for Devs

2023-02-20 12:22 UTC, Xtoseone approved these changes

2023-02-23 16:11 UTC, ArinCantCode approved these changes

2023-03-06 13:39 UTC, ArinCantCode requested changes

2023-03-06 13:39 UTC, ArinCantCode commented on src/atoms/toggles/switcher.tsx
> +      // box-shadow: ${({ disabled, theme }) => !disabled && theme.dropShadow.REGULAR};
can you remove it

2023-03-06 13:54 UTC, shan8851 commented on src/atoms/toggles/switcher.tsx
> +      // box-shadow: ${({ disabled, theme }) => !disabled && theme.dropShadow.REGULAR};
done

2023-03-06 14:22 UTC, ArinCantCode approved these changes

2023-03-07 07:31 UTC, shan8851 commented
@ArinCantCode I added `MEDIUM_BLUE` to theme, needed for hover effects on theme card

2023-03-08 11:22 UTC, closed without merging