Fe hints
uniwhales/component-library pull request #28
Opened 2022-06-15 09:56 UTC by Nuclear1Gandhi

https://uniwhales.atlassian.net/browse/FE-309

2022-06-15 10:27 UTC, shan8851 requested changes
All works as expected other than the left tooltip due to spacing

2022-06-15 10:27 UTC, shan8851 commented on src/organisms/hintsAndHovers/hintsAndHovers.stories.tsx
> +  margin-left: 100px;
With margin-left of 100px the `left` popover actually displays on the top. If you increase the margin then the left works fine, so to demonstrate all options maybe it is better to increase the margin here

2022-06-15 15:00 UTC, shan8851 requested changes

2022-06-16 08:54 UTC, shan8851 approved these changes

2022-06-16 09:28 UTC, goshatravin approved these changes

2022-06-16 09:28 UTC, merged