add card datge
uniwhales/component-library pull request #30
Opened 2022-06-17 13:44 UTC by ArinCantCode

https://uniwhales.atlassian.net/browse/FE-244

2022-06-17 15:18 UTC, shan8851 approved these changes

2022-06-19 07:14 UTC, goshatravin requested changes

2022-06-19 07:14 UTC, goshatravin commented on src/molecules/cardDate/cardDate.stories.tsx
> +  <CardDate date={date || 'Nov 31st, 2021'} state={state || 'Upcoming'} />
@ArinCantCode  all defaultValues should be stored in obj, const defaultParams = {data: "Nov 31" }

2022-06-19 07:14 UTC, goshatravin commented on src/molecules/cardDate/cardDate.tsx
> +      <Text size="L-Bold">{date}</Text>
@ArinCantCode 18 font-size ? , can u double check with Michal about it, maybe she has different point of view already , if not lets stay like this.

2022-06-20 15:12 UTC, goshatravin approved these changes

2022-06-20 15:13 UTC, merged