fix select types and tweak cards component
uniwhales/component-library pull request #41
Opened 2022-06-28 11:22 UTC by ArinCantCode

Includes fixes for: 

https://uniwhales.atlassian.net/browse/FE-358
https://uniwhales.atlassian.net/browse/FE-328

2022-06-29 06:10 UTC, goshatravin requested changes
![Screen Shot 2022-06-29 at 9 07 35](https://user-images.githubusercontent.com/35912161/176364055-c9bb8f43-7383-4b9a-9724-d1fd592dda1e.png)
@ArinCantCode  can u check, i think something with btn color

2022-06-29 17:23 UTC, ArinCantCode commented
@goshatravin that color is according to design

2022-06-29 20:32 UTC, shan8851 approved these changes

2022-06-30 06:07 UTC, goshatravin approved these changes

2022-06-30 06:07 UTC, merged