adding txtype checkbox select for action bar
uniwhales/component-library pull request #48
Opened 2022-07-11 09:42 UTC by shan8851

Tx Type select fro action bar added with checkbox. I am just confirming with Michal whether we can use existing select styles or we need new ones.

2022-07-11 10:31 UTC, shan8851 commented
I have spoken with Michal and she is happy for it to behave exactly the same as the current select component

2022-07-15 09:52 UTC, goshatravin requested changes

2022-07-15 09:52 UTC, goshatravin commented on src/organisms/actionBar/actionBar.tsx
> +          onChange={(e) => typeHandler(e as any)}
@shan8851  i think u know type of e ? no ?

2022-07-17 12:02 UTC, goshatravin approved these changes

2022-07-17 12:02 UTC, merged